import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Poppins, Lobster_Two } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";
import { Analytics } from "@vercel/analytics/react";

// Import Google Fonts with Next.js font optimization.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Import Poppins and Lobster Two from Google Fonts
const poppins = Poppins({
  weight: ["100", "400", "600"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const lobsterTwo = Lobster_Two({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-lobster-two",
});

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* No need to import external links for fonts, as we are using next/font */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${lobsterTwo.variable}  font-poppins bg-white text-black antialiased`}
      >
        <Analytics />
          <Navbar />
          {children}
          <Footer />
      </body>
    </html>
  );
}
